import argparse
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

import soundfile as sf
import torch
from PIL import Image
from diffusers.utils.loading_utils import load_image

from checkpoint_paths import SCENE_CHECKPOINT
from models.AudioConditioner import AudioConditioner
from models.BLIPModel import BLIPModel
from models.CLAPModel import CLAPModel
from models.Descriptor import TwoDeepDescriptor
from models.Img2Vid import CogVideoX
from models.StableAudioModel import StableAudioModel


ROOT_DIR = Path(__file__).resolve().parent
DEFAULT_CHECKPOINT = SCENE_CHECKPOINT
DEFAULT_OUTPUT_DIR = ROOT_DIR / "sounds"


@dataclass
class GenerationResult:
    prompt: str
    negative_prompt: str
    similarity_score: float
    silent_video_path: Path
    audio_path: Path
    final_video_path: Path


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a video from an image with CogVideoX and music generated by AudioConditioner."
    )
    parser.add_argument("--image", required=True, help="Path to the source image.")
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="Directory where audio and video files will be saved.",
    )
    parser.add_argument(
        "--checkpoint",
        default=str(DEFAULT_CHECKPOINT),
        help="Path to the trained descriptor checkpoint.",
    )
    parser.add_argument(
        "--audio-duration",
        type=float,
        default=30.0,
        help="Audio duration in seconds.",
    )
    parser.add_argument(
        "--audio-steps",
        type=int,
        default=50,
        help="Inference steps for Stable Audio.",
    )
    parser.add_argument(
        "--video-steps",
        type=int,
        default=50,
        help="Inference steps for CogVideoX image-to-video generation.",
    )
    parser.add_argument(
        "--video-fps",
        type=int,
        default=12,
        help="Output video fps for the generated silent video.",
    )
    parser.add_argument(
        "--video-seed",
        type=int,
        default=None,
        help="Optional seed for deterministic video generation. Omit for random seed.",
    )
    parser.add_argument(
        "--loop-video",
        action="store_true",
        help="Force seamless loop motion (can increase artifacts on characters).",
    )
    parser.add_argument(
        "--num-waveforms",
        type=int,
        default=1,
        help="Number of candidate audios to generate. The best one is saved.",
    )
    return parser


def load_models(
    checkpoint_path: Path,
    video_fps: int = 12,
    video_seed: int | None = None,
    loop_video: bool = False,
):
    clap_model = CLAPModel()
    music_prompter = TwoDeepDescriptor(clap_dim=512, backbone_dim=256, top_p=0.1)
    music_prompter.load_state_dict(torch.load(checkpoint_path, map_location=torch.device("cpu")))
    stable_audio_model = StableAudioModel()
    blip_model = BLIPModel()
    img2vid_model = CogVideoX(
        prompt=(
            "A cinematic photorealistic shot with stable camera and coherent body motion, "
            "high detail, physically plausible movement, no abrupt action."
        ),
        fps=video_fps,
        seed=video_seed,
        loop_video=loop_video,
    )
    audio_conditioner = AudioConditioner(stable_audio_model, music_prompter, blip_model, clap_model)
    return audio_conditioner, img2vid_model, stable_audio_model


def save_generated_audio(generated_audio: torch.Tensor, sampling_rate: int, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    audio = generated_audio[0].T.float().cpu().numpy()
    sf.write(output_path, audio, sampling_rate)
    return output_path


def sanitize_filename_stem(stem: str) -> str:
    """Normalize user-provided stems to avoid backend path parsing issues."""
    cleaned = stem.strip()
    cleaned = re.sub(r"\s+", "_", cleaned)
    cleaned = re.sub(r"[^A-Za-z0-9._-]", "", cleaned)
    return cleaned or "generated"


def merge_video_and_audio(video_path: Path, audio_path: Path, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if not video_path.exists():
        raise FileNotFoundError(f"Silent video not found before ffmpeg merge: {video_path}")
    if not audio_path.exists():
        raise FileNotFoundError(f"Audio file not found before ffmpeg merge: {audio_path}")

    command = [
        "ffmpeg",
        "-y",
        "-stream_loop",
        "-1",
        "-i",
        str(video_path),
        "-i",
        str(audio_path),
        "-c:v",
        "copy",
        "-c:a",
        "aac",
        "-shortest",
        str(output_path),
    ]

    try:
        subprocess.run(command, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as exc:
        stderr = (exc.stderr or "").strip()
        raise RuntimeError(
            "ffmpeg merge failed. "
            f"video={video_path} audio={audio_path} output={output_path}\n"
            f"ffmpeg stderr:\n{stderr}"
        ) from exc
    return output_path


def generate_video_with_music_from_image(
    image: Image.Image,
    image_stem: str,
    output_dir: Path,
    audio_conditioner: AudioConditioner,
    img2vid_model: CogVideoX,
    stable_audio_model: StableAudioModel,
    audio_duration: float,
    audio_inference_steps: int,
    video_inference_steps: int,
    num_waveforms_per_prompt: int,
) -> GenerationResult:
    output_dir.mkdir(parents=True, exist_ok=True)
    safe_image_stem = sanitize_filename_stem(image_stem)

    generated_audio, music_descriptor, dissimilarity_score = audio_conditioner(
        image,
        input_type="image",
        audio_end_in_s=audio_duration,
        num_waveforms_per_prompt=num_waveforms_per_prompt,
        num_inference_steps=audio_inference_steps,
    )

    silent_video_path = output_dir / f"{safe_image_stem}_silent.mp4"
    audio_path = output_dir / f"{safe_image_stem}_audio.wav"
    final_video_path = output_dir / f"{safe_image_stem}_with_music.mp4"

    img2vid_model.generate_and_save(image, str(silent_video_path), num_inference_steps=video_inference_steps)
    save_generated_audio(generated_audio, stable_audio_model.pipeline.vae.sampling_rate, audio_path)
    merge_video_and_audio(silent_video_path, audio_path, final_video_path)

    return GenerationResult(
        prompt=music_descriptor.prompt(),
        negative_prompt=music_descriptor.negative_prompt(),
        similarity_score=dissimilarity_score[0].item(),
        silent_video_path=silent_video_path,
        audio_path=audio_path,
        final_video_path=final_video_path,
    )


def generate_video_with_music(
    image_path: Path,
    output_dir: Path,
    checkpoint_path: Path,
    audio_duration: float,
    audio_inference_steps: int,
    video_inference_steps: int,
    num_waveforms_per_prompt: int,
    video_fps: int,
    video_seed: int | None,
    loop_video: bool,
) -> GenerationResult:
    if not image_path.exists():
        raise FileNotFoundError(f"Image not found: {image_path}")
    if not checkpoint_path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")

    audio_conditioner, img2vid_model, stable_audio_model = load_models(
        checkpoint_path,
        video_fps=video_fps,
        video_seed=video_seed,
        loop_video=loop_video,
    )
    image = load_image(str(image_path))

    return generate_video_with_music_from_image(
        image=image,
        image_stem=image_path.stem,
        output_dir=output_dir,
        audio_conditioner=audio_conditioner,
        img2vid_model=img2vid_model,
        stable_audio_model=stable_audio_model,
        audio_duration=audio_duration,
        audio_inference_steps=audio_inference_steps,
        video_inference_steps=video_inference_steps,
        num_waveforms_per_prompt=num_waveforms_per_prompt,
    )


def run_cli() -> None:
    args = build_arg_parser().parse_args()
    result = generate_video_with_music(
        image_path=Path(args.image),
        output_dir=Path(args.output_dir),
        checkpoint_path=Path(args.checkpoint),
        audio_duration=args.audio_duration,
        audio_inference_steps=args.audio_steps,
        video_inference_steps=args.video_steps,
        num_waveforms_per_prompt=args.num_waveforms,
        video_fps=args.video_fps,
        video_seed=args.video_seed,
        loop_video=args.loop_video,
    )

    print("Generated prompt:", result.prompt)
    print("Negative prompt:", result.negative_prompt)
    print("Best similarity score:", result.similarity_score)
    print("Silent video:", result.silent_video_path)
    print("Audio:", result.audio_path)
    print("Final video:", result.final_video_path)

if __name__ == "__main__":
    run_cli()