import argparse
import subprocess
from dataclasses import dataclass
from pathlib import Path

import soundfile as sf
import torch
from PIL import Image
from diffusers.utils.loading_utils import load_image

from models.AudioConditioner import AudioConditioner
from models.BLIPModel import BLIPModel
from models.CLAPModel import CLAPModel
from models.Descriptor import TwoDeepDescriptor
from models.Img2VidSD import Img2VSDModel
from models.StableAudioModel import StableAudioModel


ROOT_DIR = Path(__file__).resolve().parent
DEFAULT_CHECKPOINT = ROOT_DIR / "saves" / "model_checkpoint.pt"
DEFAULT_OUTPUT_DIR = ROOT_DIR / "sounds"


@dataclass
class GenerationResult:
    prompt: str
    negative_prompt: str
    similarity_score: float
    silent_video_path: Path
    audio_path: Path
    final_video_path: Path


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a video from an image with music generated by AudioConditioner."
    )
    parser.add_argument("--image", required=True, help="Path to the source image.")
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="Directory where audio and video files will be saved.",
    )
    parser.add_argument(
        "--checkpoint",
        default=str(DEFAULT_CHECKPOINT),
        help="Path to the trained descriptor checkpoint.",
    )
    parser.add_argument(
        "--audio-duration",
        type=float,
        default=30.0,
        help="Audio duration in seconds.",
    )
    parser.add_argument(
        "--audio-steps",
        type=int,
        default=50,
        help="Inference steps for Stable Audio.",
    )
    parser.add_argument(
        "--video-steps",
        type=int,
        default=25,
        help="Inference steps for Stable Video Diffusion.",
    )
    parser.add_argument(
        "--num-waveforms",
        type=int,
        default=1,
        help="Number of candidate audios to generate. The best one is saved.",
    )
    return parser


def load_models(checkpoint_path: Path):
    clap_model = CLAPModel()
    music_prompter = TwoDeepDescriptor(clap_dim=512, backbone_dim=256, top_p=0.1)
    music_prompter.load_state_dict(torch.load(checkpoint_path, map_location=torch.device("cpu")))
    stable_audio_model = StableAudioModel()
    blip_model = BLIPModel()
    img2vid_model = Img2VSDModel(device="cuda" if torch.cuda.is_available() else "cpu")
    audio_conditioner = AudioConditioner(stable_audio_model, music_prompter, blip_model, clap_model)
    return audio_conditioner, img2vid_model, stable_audio_model


def save_generated_audio(generated_audio: torch.Tensor, sampling_rate: int, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    audio = generated_audio[0].T.float().cpu().numpy()
    sf.write(output_path, audio, sampling_rate)
    return output_path


def merge_video_and_audio(video_path: Path, audio_path: Path, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    command = [
        "ffmpeg",
        "-y",
        "-stream_loop",
        "-1",
        "-i",
        str(video_path),
        "-i",
        str(audio_path),
        "-c:v",
        "copy",
        "-c:a",
        "aac",
        "-shortest",
        str(output_path),
    ]
    subprocess.run(command, check=True)
    return output_path


def generate_video_with_music_from_image(
    image: Image.Image,
    image_stem: str,
    output_dir: Path,
    audio_conditioner: AudioConditioner,
    img2vid_model: Img2VSDModel,
    stable_audio_model: StableAudioModel,
    audio_duration: float,
    audio_inference_steps: int,
    video_inference_steps: int,
    num_waveforms_per_prompt: int,
) -> GenerationResult:
    output_dir.mkdir(parents=True, exist_ok=True)

    generated_audio, music_descriptor, dissimilarity_score = audio_conditioner(
        image,
        input_type="image",
        audio_end_in_s=audio_duration,
        num_waveforms_per_prompt=num_waveforms_per_prompt,
        num_inference_steps=audio_inference_steps,
    )

    silent_video_path = output_dir / f"{image_stem}_silent.mp4"
    audio_path = output_dir / f"{image_stem}_audio.wav"
    final_video_path = output_dir / f"{image_stem}_with_music.mp4"

    img2vid_model.generate_and_save(image, str(silent_video_path), num_inference_steps=video_inference_steps)
    save_generated_audio(generated_audio, stable_audio_model.pipeline.vae.sampling_rate, audio_path)
    merge_video_and_audio(silent_video_path, audio_path, final_video_path)

    return GenerationResult(
        prompt=music_descriptor.prompt(),
        negative_prompt=music_descriptor.negative_prompt(),
        similarity_score=dissimilarity_score[0].item(),
        silent_video_path=silent_video_path,
        audio_path=audio_path,
        final_video_path=final_video_path,
    )


def generate_video_with_music(
    image_path: Path,
    output_dir: Path,
    checkpoint_path: Path,
    audio_duration: float,
    audio_inference_steps: int,
    video_inference_steps: int,
    num_waveforms_per_prompt: int,
) -> GenerationResult:
    if not image_path.exists():
        raise FileNotFoundError(f"Image not found: {image_path}")
    if not checkpoint_path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")

    audio_conditioner, img2vid_model, stable_audio_model = load_models(checkpoint_path)
    image = load_image(str(image_path))

    return generate_video_with_music_from_image(
        image=image,
        image_stem=image_path.stem,
        output_dir=output_dir,
        audio_conditioner=audio_conditioner,
        img2vid_model=img2vid_model,
        stable_audio_model=stable_audio_model,
        audio_duration=audio_duration,
        audio_inference_steps=audio_inference_steps,
        video_inference_steps=video_inference_steps,
        num_waveforms_per_prompt=num_waveforms_per_prompt,
    )


def run_cli() -> None:
    args = build_arg_parser().parse_args()
    result = generate_video_with_music(
        image_path=Path(args.image),
        output_dir=Path(args.output_dir),
        checkpoint_path=Path(args.checkpoint),
        audio_duration=args.audio_duration,
        audio_inference_steps=args.audio_steps,
        video_inference_steps=args.video_steps,
        num_waveforms_per_prompt=args.num_waveforms,
    )

    print("Generated prompt:", result.prompt)
    print("Negative prompt:", result.negative_prompt)
    print("Best similarity score:", result.similarity_score)
    print("Silent video:", result.silent_video_path)
    print("Audio:", result.audio_path)
    print("Final video:", result.final_video_path)