import sys
import os
# Add parent directory to Python path to import utils
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from typing import List, Union
import json
import torch
from utils.teaching_utils import MOOD_LIST, INSTRUMENTATION_LIST, RHYTHM_STYLE_LIST, STRUCTURE_LIST, PRODUCTION_STYLE_LIST, DYNAMICS_PROFILE_LIST, TEMPO_RANGE, DURATION_RANGE, KEY_MODE_LIST

ATTRIBUTES_THAT_ARE_LISTS = ["mood", "instrumentation", "production_style"]
CLASSIFICATION_ATTRIBUTES = ["mood", "key_mode", "instrumentation", "rhythm_style", "structure", "production_style", "dynamics_profile"]
REGRESSION_ATTRIBUTES = ["energy", "valence", "tempo", "harmonic_tension", "texture_density", "duration"]

class MusicDescriptor:
    """
    A class to encapsulate the various attributes of the music that needs to be generated by Stable Audio.

    Attributes:
    - mood: A list of strings describing the mood of the music (e.g., "dark", "epic", "melancholic").
    - energy: A float between 0 and 1 indicating the energy level of the music (0 = very calm, 1 = very energetic).
    - valence: A float between 0 and 1 indicating the valence of the music (0 = very negative/sad, 1 = very positive/happy).
    - tempo: An integer representing the tempo of the music in beats per minute (BPM).
    - key_mode: A string indicating the musical key and mode (e.g., "major", "minor", "ambiguous").
    - harmonic_tension: A float between 0 and 1 indicating the harmonic tension of the music (0 = very consonant, 1 = very dissonant).
    - instrumentation: A list of strings describing the instruments used in the music (e.g., "low strings", "brass", "war drums"...).
    - rhythm_style: A string describing the rhythm style of the music (e.g., "sparse", "pulsing", "syncopated"...).
    - structure: A string describing the structure of the music (e.g., "slow-build -> climax", "loop-based"...).
    - texture_density: A float between 0 and 1 indicating the density of the musical texture (0 = very sparse, 1 = very dense).
    - production_style: A list of strings describing the production style of the music (e.g., "lo-fi", "cinematic", "electronic"...).
    - dynamics_profile: A string describing the dynamics profile of the music (e.g., "gradual build", "sudden drops", "consistent energy"...).
    - duration: An integer representing the desired duration of the music in seconds.
    """

    def __init__(self,
                mood: Union[List[str], None],
                energy: Union[float, None],
                valence: Union[float, None],
                tempo: Union[int, None],
                key_mode: Union[str, None],
                harmonic_tension: Union[float, None],
                instrumentation: Union[List[str], None],
                rhythm_style: Union[str, None],
                structure: Union[str, None],
                texture_density: Union[float, None],
                production_style: Union[List[str], None],
                dynamics_profile: Union[str, None],
                duration: Union[int, None],
                excluded_elements: Union[List[str], None] = None,
                unwanted_moods: Union[List[str], None] = None,
                quality_preset: bool = True, # Pour inclure par défaut des tags de qualité
                **kwargs):

        self.mood = mood
        self.energy = energy
        self.valence = valence
        self.tempo = tempo
        self.key_mode = key_mode
        self.harmonic_tension = harmonic_tension
        self.instrumentation = instrumentation
        self.rhythm_style = rhythm_style
        self.structure = structure
        self.texture_density = texture_density
        self.production_style = production_style
        self.dynamics_profile = dynamics_profile
        self.duration = duration
        self.excluded_elements = excluded_elements
        self.unwanted_moods = unwanted_moods
        self.quality_preset = quality_preset

    def negative_prompt(self) -> str:
        """
        Génère la chaîne de caractères pour le negative prompt.
        """
        neg_elements = []

        # 1. Éléments techniques (Presets de qualité)
        if self.quality_preset:
            neg_elements.extend(["low quality", "mono", "distorted", "clipping", "noise", "hiss"])

        # 2. Moods indésirables
        if self.unwanted_moods:
            neg_elements.extend(self.unwanted_moods)

        # 3. Éléments musicaux à exclure
        if self.excluded_elements:
            neg_elements.extend(self.excluded_elements)

        return ", ".join(neg_elements).strip()
    
    def inv_to_range_int(self, value, min_val, max_val):
        """
       Converts an integer in the specified range to a normalized value between 0 and 1.
        """
        if value is None:
            return None
        return (value - min_val) / (max_val - min_val) if max_val > min_val else 0.0

    def to_differentiable_tensor(self):
        output = {}
        for attribute in self.__dict__:
            value = getattr(self, attribute)
            if isinstance(value, list):
                # For list attributes, we can create a multi-hot encoded tensor based on predefined lists of possible values
                possible_values = globals().get(f"{attribute.upper()}_LIST", [])
                tensor = torch.zeros(len(possible_values))
                for item in value:
                    if item in possible_values:
                        index = possible_values.index(item)
                        tensor[index] = 1.0
                output[attribute] = tensor
            elif isinstance(value, str):
                # For string attributes, we can create a one-hot encoded tensor based on predefined lists of possible values
                possible_values = globals().get(f"{attribute.upper()}_LIST", [])
                tensor = torch.zeros(len(possible_values))
                if value in possible_values:
                    index = possible_values.index(value)
                    tensor[index] = 1.0
                output[attribute] = tensor
            elif isinstance(value, (float, int)):
                # For scalar attributes, we can directly convert them to tensors
                output[attribute] = torch.tensor(value, dtype=torch.float32)
                if attribute == "tempo":
                    output[attribute] = self.inv_to_range_int(output[attribute], *TEMPO_RANGE)
                elif attribute == "duration":
                    output[attribute] = self.inv_to_range_int(output[attribute], *DURATION_RANGE)

            else:
                output[attribute] = None  # Non-differentiable attributes can be set to None or handled separately


        return output

    def energy_descriptor(self):
        """
        Converts the energy value into a qualitative descriptor. The mapping is as follows:
        - 0.0 to 0.2: "very calm"
        - 0.2 to 0.4: "calm"
        - 0.4 to 0.6: "moderate energy"
        - 0.6 to 0.8: "energetic"
        - 0.8 to 1.0: "very energetic"
        """
        if self.energy is None:
            return None
        elif self.energy < 0.2:
            return "very calm"
        elif self.energy < 0.4:
            return "calm"
        elif self.energy < 0.6:
            return "moderate energy"
        elif self.energy < 0.8:
            return "energetic"
        else:
            return "very energetic"
        

    def valence_descriptor(self):
        """
        Converts the valence value into a qualitative descriptor. The mapping is as follows:
        - 0.0 to 0.2: "very negative/sad"
        - 0.2 to 0.4: "negative/sad"
        - 0.4 to 0.6: "neutral"
        - 0.6 to 0.8: "positive/happy"
        - 0.8 to 1.0: "very positive/happy"
        """
        if self.valence is None:
            return None
        elif self.valence < 0.2:
            return "very negative/sad"
        elif self.valence < 0.4:
            return "negative/sad"
        elif self.valence < 0.6:
            return "neutral"
        elif self.valence < 0.8:
            return "positive/happy"
        else:
            return "very positive/happy"
    
        
    def harmonic_tension_descriptor(self):
        """
        Converts the harmonic tension value into a qualitative descriptor. The mapping is as follows:
        - 0.0 to 0.2: "very consonant"
        - 0.2 to 0.4: "consonant"
        - 0.4 to 0.6: "balanced"
        - 0.6 to 0.8: "dissonant"
        - 0.8 to 1.0: "very dissonant"
        """
        if self.harmonic_tension is None:
            return None
        elif self.harmonic_tension < 0.2:
            return "very consonant"
        elif self.harmonic_tension < 0.4:
            return "consonant"
        elif self.harmonic_tension < 0.6:
            return "balanced"
        elif self.harmonic_tension < 0.8:
            return "dissonant"
        else:
            return "very dissonant"
        
        
    def structure_density_descriptor(self):
        """
        Converts the texture density value into a qualitative descriptor. The mapping is as follows:
        - 0.0 to 0.2: "very minimal"
        - 0.2 to 0.4: "minimal"
        - 0.4 to 0.6: "moderately layered"
        - 0.6 to 0.8: "layered"
        - 0.8 to 1.0: "very layered"
        """
        if self.texture_density is None:
            return None
        elif self.texture_density < 0.2:
            return "very minimal"
        elif self.texture_density < 0.4:
            return "minimal"
        elif self.texture_density < 0.6:
            return "moderately layered"
        elif self.texture_density < 0.8:
            return "layered"
        else:
            return "very layered"
    
    
    def prompt(self):
        """
        Builds a descriptive prompt string based on the attributes of the music descriptor. Only includes attributes that are not None.
        The structure of the prompt is as follows:
        - Sentence 1: production_style / genre
        - Sentence 2: mood + valence + energy + density
        - Sentence 3: instrumentation
        - Sentence 4: tempo + rhythm
        - Sentence 5: harmony + tension 
        - Sentence 6: structure + dynamics
        - Sentence 7: constraints
        """


        sentences = []

        # Sentence 1: production style / genre

        sentence = ""

        if self.production_style:
            sentence += f"{', '.join(self.production_style).capitalize()} music."

        if sentence:
            sentences.append(sentence)
        
        # Sentence 2 : mood + valence + energy + density

        sentence = ""

        if self.mood:
            sentence += f"{', '.join(self.mood).capitalize()} mood"

        valence_desc = self.valence_descriptor()
        if valence_desc:
            if sentence:
                sentence += f", {valence_desc} music"
            else:
                sentence += f"{valence_desc.capitalize()} music"
        
        energy_desc = self.energy_descriptor()
        if energy_desc:
            if sentence:
                sentence += f", {energy_desc}"
            else:
                sentence += f"{energy_desc.capitalize()} music"
        
        density_desc = self.structure_density_descriptor()
        if density_desc:
            if sentence:
                sentence += f", with a {density_desc} texture"
            else:
                sentence += f"{density_desc.capitalize()} texture"
        
        if sentence:
            sentence += "."
            sentences.append(sentence)

        # Sentence 3: instrumentation

        sentence = ""

        if self.instrumentation:
            sentence += f"Featuring {', '.join(self.instrumentation)}."

        if sentence:
            sentences.append(sentence)
        
        # Sentence 4: tempo + rhythm

        sentence = ""

        if self.tempo:
            sentence += f"Tempo around {self.tempo} BPM"
        if self.rhythm_style:
            if sentence:
                sentence += f", with a {self.rhythm_style} rhythm"
            else:
                sentence += f"Rhythm style: {self.rhythm_style}"

        if sentence:
            sentence += "."
            sentences.append(sentence)
        
        # Sentence 5: harmony + tension

        sentence = ""
        if self.key_mode:
            if self.key_mode in ["major", "minor"]:
                sentence += f"In a {self.key_mode} key"
            else:
                sentence += f"In an {self.key_mode} key"
        
        harmonic_tension_desc = self.harmonic_tension_descriptor()
        if harmonic_tension_desc:
            if sentence:
                sentence += f", with a {harmonic_tension_desc} tension"
            else:
                sentence += f"Harmonic tension: {harmonic_tension_desc}"
        if sentence:
            sentence += "."
            sentences.append(sentence)
        
        # Sentence 6: structure + dynamics
        sentence = ""

        if self.structure:
            sentence += f"The structure is {self.structure}"
        
        if self.dynamics_profile:
            if sentence:
                sentence += f", with a {self.dynamics_profile}"
            else:
                sentence += f"The song should have a {self.dynamics_profile} dynamics profile"
        
        if sentence:
            sentence += "."
            sentences.append(sentence)
        
        # Sentence 7: constraints
        sentence = ""

        if self.duration:
            sentence += f"Duration around {self.duration} seconds"
        
        if sentence:
            sentence += "."
            sentences.append(sentence)
        
        return " ".join(sentences).strip()
    

def read_music_descriptor_from_json(json_str: str) -> tuple[str, MusicDescriptor]:
    data = json.loads(json_str)
    descriptor = data.get("descriptor", {})
    scene = data.get("scene", "unknown_scene")
    descriptor["tempo"] = descriptor["tempo_bpm"] 
    descriptor["duration"] = descriptor["duration_s"]  
    descriptor.pop("tempo_bpm", None)
    descriptor.pop("duration_s", None)
    return scene, MusicDescriptor(**descriptor)

if __name__ == "__main__":
    # Exemple d'utilisation
    dataset_path = "data/teacher_dataset.jsonl"
    with open(dataset_path, "r") as f:
        first_line = f.readline()
    scene, descriptor = read_music_descriptor_from_json(first_line)
    print(f"Scene: {scene}")
    print(f"Generated Prompt: {descriptor.prompt()}")
    print(f"Generated Negative Prompt: {descriptor.negative_prompt()}")
    print(f"Differentiable Tensor: {descriptor.to_differentiable_tensor()}")